name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Download java 17 jdk
        run: sudo apt-get install -y openjdk-17-jdk
      - name: build the app
        run: ./gradlew build
